### ISSUE TITLE
Feature Request: abortable

### ISSUE THREAD

**Issue by toastal** [Daninet/hash-wasm#10]
As `Promise`s the general hashing APIs is to represent an asynchronous value. In many case, say hashing a large video file, the ability to cancel such computation would be nice.

[AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) + [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal) would allow these functions to be canceled/aborted. This is one of the flaws of using Promises as an API as it is unergonomic to add the ability to abort unlike a `Future` or `Aff`.

**Comment by Daninet** [comment]
By default, WebAssembly is executed on the main thread. The only thing, which is parallelized, is the compilation of the binary:  Chrome doesn't allow compiling larger binaries than 4kb in a sync manner. I also did some experiments running the hash calculation in Web Workers, but the communication latency is too high to be worth it. So the only reason, why hash-wasm is using promises, is because the restrictions imposed by the browser APIs.

Why would you need cancelation? In my point of view, the streaming input (createXYZ() functions) can be already used to hash large files in smaller blocks. You can stop anytime feeding update() with new chunks.

**Comment by toastal** [comment]
>  You can stop anytime feeding update() with new chunks.

I guess I didn't think about that. I need to wrap these computations in asynchronous effects for another library, and as a part of the async effect spec, I need to be able to cancel. I will probably use the `update` then. I can't say I fully understand the performance characteristics of making new Wasm instance as noted in the README, but it does appear to be the way to run it in parallel.

It's good to know that the worker option wasn't valuable in many cases. Thanks.
