### ISSUE TITLE
How to pull in only a subset of algos via npm?

### ISSUE THREAD

**Issue by namero999** [Daninet/hash-wasm#11]
Is this supposed to be taken care of via tree-shaking at build time?

```js
"dependencies": {
    "hash-wasm": "latest"
}

import { md5 } from 'hash-wasm'
```

Or is there a better way?

Thanks!

**Comment by Daninet** [comment]
If tree shaking is enabled in your Webpack configuration, it will only bundle the md5 algorithm in the way you described.

Otherwise, you can directly import the md5 bundle: 
`import { md5 } from 'hash-wasm/dist/md5.umd.min.js`
I don't recommend it, because the types declarations are not working in this case.
