### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by zdm** [Daninet/hash-wasm#2]
My tests shows other values:
```
jssha-sha1      - 135972.15 iterations / second (100000 / 0.74 sec.)
wasm-sha1       - 38596.03 iterations / second (100000 / 2.59 sec.)
```

Test is simple hash calc. func, called in loop.
### jssha
```
const hash = new jsSHA( "SHA-1", "BYTES" );
hash.update( str );
hash.getHash( "HEX" );
```
### hash-wasm
```
await sha1( str );
```
What I am doing wrong?

**Comment by Daninet** [comment]
I ran some additional tests and I managed to reproduce your results. It seems that for small input buffers jsSHA is much faster in SHA-1.

Here are my measurements:
16 bytes => jssha is about 2.6x faster
256 bytes => jssha has similar performance compared to hash-wasm
1024 bytes => hash-wasm is about 2x faster
32 kilobytes => hash-wasm is about 7.7x faster

My benchmarks were run on a 4MB input buffer. That's why we see a big difference there.
Thank you for bringing up this issue. I will add some additional columns to the benchmark section to also compare the performance of hashing smaller chunks of data.

**Comment by zdm** [comment]
ok, thank you for clarifying,

**Comment by Daninet** [comment]
I found a way to improve the performance for smaller input.
You can check it out in v3.0.1.

Also, I added a new column with the 32 byte benchmark results.

**Comment by zdm** [comment]
Yes, I see, Thank you.
Interesting, why your code is slow on small data?

**Comment by zdm** [comment]
You forgot to remove console.log from code.
```
await sha1( "123" );
```
prints to console.

**Comment by Daninet** [comment]
I improved the performance further in version 3.1.1. Now it should be at least 2 times faster than jsSHA  for short input strings.

I cannot reproduce the `console.log` issue. I don't have console.logs in the code.

**Comment by Daninet** [comment]
The bottleneck is the JavaScript -> WebAssembly boundary. Currently, the WASM function calls from JavaScript are very expensive. I managed to increase the performance by decreasing the number of WASM calls from 3 to 1 in case of small input data. 

I think, that in the future these bottlenecks will disappear, while the JavaScript engine developers implement further optimizations for WASM.

**Comment by zdm** [comment]
Thank you, performance is amazing now.
