### ISSUE TITLE
Feature Request: BLAKE3

### ISSUE THREAD

**Issue by Cavitt** [Daninet/hash-wasm#4]
Any chance https://github.com/BLAKE3-team/BLAKE3 could be implemented?
Though, most of the performance benefits would probably be from SIMD (I assume?).
I'm not sure how fleshed out SIMD is in WebAssembly, last time I checked V8 had buggy support.
Either way, it would be interesting to see the performance difference with Blake2b in WASM.

**Comment by Daninet** [comment]
SIMD in WebAssembly is in Origin Trial since last month, so I estimate that we need at least a year until we can use it. It will definitely increase the performance.

BLAKE3 is a fairly new algorithm. I was considering adding it, but I could not find any high-profile projects using it. Do you have some examples?
I want to prioritize adding algorithms, which are widely used. Currently I'm working on Argon2 support.

**Comment by Cavitt** [comment]
> Do you have some examples?

I don't, I do have plans to use it in a production app for hashing & comparing large files.

**Comment by Daninet** [comment]
BLAKE3 landed in v4.5.0
The performance is similar to blake2b because the SIMD support is still missing from the browsers.
